In [2]:
import tensorflow as tf

##Tensorflow Basics

In [4]:
#defining constants

x = tf.constant([[5,2],[3,2]])
print(x)
print(x.numpy())


tf.Tensor(
[[5 2]
 [3 2]], shape=(2, 2), dtype=int32)
[[5 2]
 [3 2]]


In [8]:
print(tf.ones(shape=(2, 3,3)))
print(tf.zeros(shape=(2, 3,3)))

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 3, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 3, 3), dtype=float32)


In [17]:
variable = tf.random.uniform(shape=(2, 2), minval=0,maxval=10,dtype='int32')
tf_var = tf.Variable(variable)

print(tf_var)


<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[0, 2],
       [1, 6]], dtype=int32)>


# **Math**

In [31]:
a = tf.ones(shape=(2, 2),dtype='int32')
b = tf.random.uniform(shape=(2, 2), minval=0,maxval=10,dtype='int32')

print(a*b)
print(tf.square(b))


tf.Tensor(
[[4 0]
 [6 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[16  0]
 [36 25]], shape=(2, 2), dtype=int32)


In [7]:
print(tf.math.add(1, 2))
print(tf.math.add([1,2],[3,4]))
print(tf.math.reduce_sum([1, 2, 3]))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [10]:
x = tf.linalg.matmul([[1],[4]], [[2, 3]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor(
[[ 2  3]
 [ 8 12]], shape=(2, 2), dtype=int32)
(2, 2)
<dtype: 'int32'>


## Reshape

In [35]:
tensor1 = tf.constant([[[1,3,4],[5,3,2]],[[2,3,4],[6,3,2]],[[10,3,40],[5,30,2]]])
tensor1

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  3,  4],
        [ 5,  3,  2]],

       [[ 2,  3,  4],
        [ 6,  3,  2]],

       [[10,  3, 40],
        [ 5, 30,  2]]], dtype=int32)>

In [36]:

tensor2 = tf.reshape(tensor1, [3,3,2])  # reshape existing data 

tensor2


<tf.Tensor: shape=(3, 3, 2), dtype=int32, numpy=
array([[[ 1,  3],
        [ 4,  5],
        [ 3,  2]],

       [[ 2,  3],
        [ 4,  6],
        [ 3,  2]],

       [[10,  3],
        [40,  5],
        [30,  2]]], dtype=int32)>

In [45]:
tf_var = tf.constant([1,3,5,7,8,10,15,20,34])
print(tf_var)

tf_var[0].numpy()
tf_var[-7].numpy()

tf.Tensor([ 1  3  5  7  8 10 15 20 34], shape=(9,), dtype=int32)


5

In [53]:
print(tf_var[1:5].numpy())
print(tf_var[4:].numpy())
print(tf_var[::2].numpy()) # every other item
print(tf_var[::3].numpy())# every 3rd item



[3 5 7 8]
[ 8 10 15 20 34]
[ 1  7 15]


In [19]:
a = tf.ones(shape=(2,2))
b = tf.ones(shape=(2,2))
a_tfvar = tf.Variable(a)

In [12]:
a_tfvar.assign(b)

for i in range(2):
  for j in range(2):
    print(a_tfvar[i,j])
    print(b[i,j])
    assert a_tfvar[i,j] == b[i,j]


tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)


In [16]:
a_tfvar.assign_add(b)

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [20]:
a_tfvar.assign_sub(b)

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

# Matrix Multiplication

In [25]:
m1 = tf.constant([[1],[2]])
print(m1.shape)
m2 = tf.constant([[1,2]])
print(m2.shape)

(2, 1)
(1, 2)


## Tensorflow Einsum

In [3]:
m0 = tf.random.normal(shape=(3,2))
m1 = tf.random.normal(shape=(2,3))

e = tf.einsum('ij,jk ->ik',m0,m1)
print(e.shape)
print(e)

(3, 3)
tf.Tensor(
[[-0.35070992  0.10430431 -0.77833676]
 [-1.4679887   3.6189022  -0.87968683]
 [ 0.95341337 -1.006741    1.5754651 ]], shape=(3, 3), dtype=float32)


In [5]:
m0 = tf.random.normal(shape=(3,2))
m1 = tf.random.normal(shape=(2,1))

e = tf.einsum('ij,jk ->ki',m0,m1)
print(e.shape)
print(e)

(1, 3)
tf.Tensor([[ 0.00313315 -2.204155    0.9246214 ]], shape=(1, 3), dtype=float32)


In [9]:
m0 = tf.random.normal(shape=[5])
m1 = tf.random.normal(shape=[5])

print(m0)

e=tf.einsum('i,i->',m0,m1)

print(e)


tf.Tensor([ 1.5152853  -0.01245665 -0.6864052  -0.75580317  0.20671712], shape=(5,), dtype=float32)
tf.Tensor(0.10716015, shape=(), dtype=float32)


In [11]:
m0 = tf.random.normal(shape=[2])
m1 = tf.random.normal(shape=[5])

print(m0)
print(m1)

e=tf.einsum('i,j->ij',m0,m1)

print(e)


tf.Tensor([-0.5114267  -0.15820399], shape=(2,), dtype=float32)
tf.Tensor([-0.5299457   0.00258639 -0.18228339  0.19975963  0.08145297], shape=(5,), dtype=float32)
tf.Tensor(
[[ 0.27102837 -0.00132275  0.09322459 -0.10216241 -0.04165722]
 [ 0.08383952 -0.00040918  0.02883796 -0.03160277 -0.01288618]], shape=(2, 5), dtype=float32)
