In [1]:
import tensorflow as tf



In [8]:

import numpy as np
arr = [1,2,3]

print(arr)
print(tf.shape(arr))

print(tf.range(tf.shape(arr)[0]))


[1, 2, 3]
tf.Tensor([3], shape=(1,), dtype=int32)
tf.Tensor([0 1 2], shape=(3,), dtype=int32)


# Linear Search

In [9]:
def linear_search(arr, target):
    """
    Searches for a target element in a 1D tensor using linear search algorithm.
    """
    indices = tf.range(tf.shape(arr)[0])
    mask = tf.equal(arr, target)
    # create a boolean tensor to mark where the target is found
    matches = tf.boolean_mask(indices, mask)
    # get the indices where target is found
    return tf.cond(tf.size(matches) > 0, lambda: matches[0], lambda: -1)
    # return the first match, or -1 if no match is found


# Insertion Sort

In [10]:
import tensorflow as tf

def insertion_sort(arr):
    """
    Sorts a 1D tensor in ascending order using insertion sort algorithm.
    """
    for i in tf.range(1, tf.shape(arr)[0]):
        key = arr[i]
        j = i - 1
        while j >= 0 and key < arr[j]:
            arr = tf.tensor_scatter_nd_update(arr, [[j+1]], [arr[j]])
            j -= 1
        arr = tf.tensor_scatter_nd_update(arr, [[j+1]], [key])
    return arr


In [11]:
import tensorflow as tf

def binary_search(arr, target):
    """
    Searches for a target element in a 1D tensor using binary search algorithm.
    """
    low = tf.constant(0)
    high = tf.shape(arr)[0] - 1

    while low <= high:
        mid = (low + high) // 2
        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            low = mid + 1
        else:
            high = mid - 1
    return -1


In [17]:
array = [1,2,4,5,11,5,3]

print(binary_search(array,3))

-1


In [18]:
print(insertion_sort(array))

tf.Tensor([ 1  2  3  4  5  5 11], shape=(7,), dtype=int32)


In [21]:
print(linear_search(array,11))

tf.Tensor(4, shape=(), dtype=int32)
